name: AutoBot Workflow

on: push

jobs:
  AutoBot-Issue:
    # Below example workflow creates an issue using the GitHub REST API
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/$GITHUB_REPOSITORY/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }} ",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}** . \n\n The commit hash was:_${{ github.sha }}_. "
            }' \
          --fail
  
  AutoBot-Commit:
    # Creates an autocommit for a file.
    # So basically we will initialize a repository on runner and commit a new file which has random numbers
    # using RANDOM bash command. After committing we will push it to origin.
    runs-on: ubuntu-latest
    steps:
      - name: AutoBot Commit by Codophillic-Bot
        run: |
          pwd
          ls -a 
          mkdir AutoCommitFolder
          ls -a 
          cd AutoCommitFolder
          git init
          git remote add origin 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
          git config user.name "Codophilic-bot"
          git config user.email "Codophilic-bot@bot.com"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> randomfile.txt
          git add .
          git commit -m 'Codophilic Bot committed randomfile.txt'
          git push 
          
          





