name: Container YAML

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.15
      # Here we can add ports,volumes,env etc. details
    steps:
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release