name: Before deploying react application pull request status check test cases

on: 
  pull_request:
    branches:
      - develop

jobs:
  TESTCASES:
    runs-on: ubuntu-latest
    env:
      path: ./ReactApplication/my-react-application/
    steps:
      - name: Checkout the repositories
        uses: actions/checkout@v2
      - name: set-up a specific node version on runner
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Installing Dependencies
        run: |
          cd ${{ env.path }}
          npm ci 
      - name: Check Prettier Formats
        run: |
          cd ${{ env.path }}
          npm run format:check
      - name: Run Automated test for Code coverage
        run: |
          cd ${{ env.path }}
          npm test -- --coverage
        env:
          CI: true


