name: Environment Variables

on: [ push, pull_request ]

# Environment variable (Global sort of for ALL JOBS) (applicable to whole workflow)
# Defining en variables always use underscore and not hypen.
env:
  Workflow_ENV: Available to all JOBS

jobs:
  Print-Define-ENV-Variables: #JOB1
    runs-on: ubuntu-latest
    # Applying EVN for particular JOB (local sort of at JOB level) ( applicable to only particular JOB)
    env:
      Local_ENV: Available to JOB1 only and for all steps of JOB1
    steps:
      - name: ECHO ENV Variables for STEP-1
      # Applying ENV for particular step (local sort of at STEP level ) (applicable to only particular step of a JOB)
        env:
          step_ENV_variable: Available to only this step
        run: |
          echo "Global Variable: ${Workflow_ENV} "
          echo " Local Variable at JOB level: ${Local_ENV} "
          echo " Local Variable at step lebel: ${step_ENV_variable} "
      - name: ECHO ENV Variables of STEP-1
        run: |
          echo "Global Variable: ${Workflow_ENV} (True)"
          echo " Local Variable at JOB level: ${Local_ENV} (True)"
          echo " Local Variable at step lebel: ${step_ENV_variable} (False)"
  
  Print-Default-ENV-Variables:
    runs-on: ubuntu-latest
    steps:
      - name: Default ENV variables provided by GitHub Actions
        run: |
          echo "HOME Directory: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "Global Variable: ${Workflow_ENV} (True)"
          echo " Local Variable at JOB level: ${Local_ENV} (False)"
          echo " Local Variable at step lebel: ${step_ENV_variable} (False)"



