# Here in this workflow we will be running commands on any events.

name: Manual Trigger workflow_dispatch

# Manual Trigger workflow on events
# Trigger workflow manually using 'repository_dispatch' or 'workflow_dispatch'
# Using workflow_dispatch we can manually trigger a workflow run using the GitHub API, GitHub CLI, or GitHub browser interface. 
# We can define custom inputs.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# When inputs are defined we need to mentioned the required state of that input so that it will show in
# manual trigger workflow.
# required: true is like a mandatory field when we see on GitHub browser.
# Now here input 'manual' has a description 'Triggered' which will be shown as required field and value as
# 'Triggering manually'.

on:
  workflow_dispatch:
    inputs:
      manual:
        description: "Triggered"
        required: true
        default: 'Triggering manually'
      branch_env:
        description: "Branch name"
        required: true
        default: 'main'
      commitID:
        description: 'Commit ID'
        required: false
        default: 'latest'


# Run the jobs after triggering (List of steps)
jobs:
  Manual-Trigger-JOB: # JOB-1 name
    runs-on: ubuntu-latest
    steps:
      - name: Manual Trigger event # STEP-1 name
        run: echo "GitHub Actions Manual Trigger" # Here the runner is ubuntu which will default use bash commands.
      - name: inputs of the workflow_dispatch
        env:
          INPUT1: ${{ inputs.manual }}
          INPUT2: ${{ inputs.manual }}
          INPUT3: ${{ inputs.branch_env }}
          INPUT4: ${{ inputs.branch_env}}
        run: |
          echo "first input: $INPUT1"
          echo "second input: $INPUT2"
          echo "third input: $INPUT3"
          echo "fourth input: $INPUT4"

